apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice-deploy
  labels: 
    app: orderservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
      - name: orderservice
        image: 10.190.34.23:5000/orderservice:v1
        ports:
        - containerPort: 8488
