apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-deploy
  labels: 
    app: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
      - name: userservice
        image: 10.190.34.23:5000/userservice:v1
        ports:
        - containerPort: 8888
